### ISSUE TITLE
Notification window borders look weird with cursorline

### ISSUE THREAD

**Issue by diegoulloao** [j-hui/fidget.nvim#117] opened 2023-01-01 18:33 UTC
https://user-images.githubusercontent.com/45423661/210181223-26a3ef35-95b0-4b17-a80d-fec9f2986c77.mov

The boxes seems to be transparent or something, I've tried so play with the `zindex` value from `50-350` and the `relative` option but doesn't work. Always you can see the cursor behind and looks weird.

I either don't see an option to add background to the boxes.

**Comment by j-hui** [comment] 2023-06-10 06:36
Yuck. I won't fix this on `legacy` but I will try to address this in the rewrite.

**Comment by j-hui** [comment] 2023-11-11 03:41
Yuck, yuck, yuck. I think I've figured out what the problem is. (By the way, `zindex` has nothing to do with it. That controls the window stacking order, but doesn't say about how their highlights should combine.)

When you have a floating window with a border, like on the left, it will be highlighted as indicated on the right:

```
         .......
 ┌───┐   .*****.
 │ a │   .*///*.
 │   │   .*///*.
 └───┘   .*****.
         .......
```

where `/` is `NormalFloat` or `NormalNC`, `*` is `FloatBorder`, and `.` is whatever highlight is surrounding window (e.g.,, `Normal`). (Fidget maps `NormalNC` to `Comment`, but I don't think that's relevant for this issue.)

Fidget also sets the `winblend` option of the floating window to `100` (now by default), which essentially disables the background color of the `/` highlight, and have it inherit the background from `.`. So, when `.` has its background highlighted due to `cursorline` or something, `/` inherits that too.

The problem is `*` doesn't seem to respect `winblend`. In other words, `winblend` only applies to the contents of the window, but not its borders.

So to address this issue, I might to fix this behavior in Neovim (or propose another option if this is supposed to be intentional). Let me file an issue there and see.

**Comment by j-hui** [comment] 2023-11-11 22:19
Fixed on nightly by https://github.com/neovim/neovim/pull/25981

**Closed by j-hui** 2023-11-11 22:19 UTC
Labels: bug, ui
