### ISSUE TITLE
nil on task name after opening telescope window in the middle of a running task

### ISSUE THREAD

**Issue by fitrh** [j-hui/fidget.nvim#79] opened 2022-05-14 12:33 UTC
https://user-images.githubusercontent.com/55179750/168425846-b3737af7-acef-4f9f-96c7-398a481166b4.mp4

Is this expected or an issue ?

Tell me if you need something to reproduce this issue

**Comment by j-hui** [comment] 2022-05-14 17:34
Yeah this is definitely a bug. I noticed it before too but never got around to tracking down the specific cause, which seems to be caused by switching to a different window.

I don't quite have time to fix this just now but thank you for bringing it up.

**Comment by j-hui** [comment] 2023-11-10 01:18
Hopefully this was fixed by #143, but if not, please re-open. With the new implementation, these kinds of bugs should be easier to test and reproduce now.

**Closed by j-hui** 2023-11-10 01:18 UTC
Labels: bug
