### ISSUE TITLE
Status sometimes get permanently stuck on the screen

### ISSUE THREAD

**Issue by thallada** [j-hui/fidget.nvim#135] opened 2023-07-18 17:27 UTC
Occasionally the fidget status will get stuck and permanently stay on the screen and there's no way to clear it. Even closing the buffer does not clear it. I have to exit neovim entirely and restart to get rid of it. It's just stuck in the place that it originally appeared and even if I move the splits around so there's text displayed there, it still shows up under the code in the split.

![Screen Shot 2023-07-18 at 1 23 01 PM](https://github.com/j-hui/fidget.nvim/assets/1505923/b35f5aae-7116-4b77-8eaf-375ebff31567)

![Screen Shot 2023-07-18 at 1 24 44 PM](https://github.com/j-hui/fidget.nvim/assets/1505923/34df97ab-7f69-437f-8dcd-9c3f3a6acaa8)

I use neovim inside Neovide 0.10.4.

Ideally I'd like it to not get stuck, but alternatively, if there's a command I could run to clear the text, that would also be really helpful to know.

**Comment by j-hui** [comment] 2023-07-18 23:14
Interesting, this is probably a bug on my end. Have you tried using `FidgetClose`? (It’s not very well-tested/robust but it was designed for this kind of a scenario.)

The progress message text is being displayed from a read-only Vim window, so you _might_ also be able to just close it by switching focus to it and then running `:q`.

But this is ultimately likely due to a window/buffer lifetime mismanagement that I hope to address in my plugin rewrite.

**Comment by thallada** [comment] 2023-07-20 20:26
I tried running `:FidgetClose` which didn't clear the text. I also tried clicking into the fidget window, but I can't seem to get focus into it. I wonder if this is just a bug with Neovide...

**Comment by j-hui** [comment] 2023-11-10 00:58
The new way I'm handling this kind of thing via `fidget.notification.suppress()` should fix the problem, or at least make it less flaky/more reproducible. This will be closed after I merge in #143 (though for now, you'll need to define your own `:FidgetClose` command), but feel free to re-open if it comes up again.

**Closed** 2023-11-10 01:15 UTC
Labels: bug
