### ISSUE TITLE
Error with gopls

### ISSUE THREAD

**Issue by ssoriche** [j-hui/fidget.nvim#19] opened 2022-01-27 20:18 UTC
I'm receiving the following error message when editing Go with gopls running:

```
Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:77: invalid option '%544' to 'format'
stack traceback:
        [C]: in function 'format'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:77: in function 'fmt'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:153: in function ''
        vim.lua: in function ''
        vim.lua: in function <vim.lua:0>
Press ENTER or type command to continue
```

The error repeats over and over again, so far I haven't been able to find the end of it.

**Comment by ssoriche** [comment] 2022-01-27 20:59
I was able to determine that the value of `pad` at `fidget.lua:77` is `%5445s` which leads me to believe that the value accepted by `string.format()` has a maximum.

**Comment by j-hui** [comment] 2022-01-27 22:51
Gopls must be making some enormous progress to warrant some 5445-character long message...

There's obviously no way that even fits on a screen, so I'll probably just cap it at some sane amount, but that does beg the question: what should the behavior be when we encounter these kinds of unreasonably long messages? Should I just truncate it?

**Comment by ssoriche** [comment] 2022-01-28 00:41
I used `%99s` when the length was longer than 99, I think this too is too long. It appears that gopls is finding some symlinks in the repository I'm working on and letting me know that it isn't going to follow them.

I could probably print the whole line to know of certain what it is getting stuck on.

I think truncating is a reasonable result, perhaps with an ellipse to indicate such.

**Comment by ttys3** [comment] 2022-01-28 13:23
I got this too.

edit `go.mod` with wrong format or value:

```
Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:77: invalid option '%161' to 'format'
stack traceback:
        [C]: in function 'format'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:77: in function 'fmt'
        ...e/nvim/site/pack/packer/start/fidget.nvim/lua/fidget.lua:153: in function ''
        vim.lua: in function ''
        vim.lua: in function <vim.lua:0>
```

**Comment by j-hui** [comment] 2022-01-28 13:32
@ttys3 can you check out the `truncate-messages` branch and see if that fixes your problem? Or at least provide a public repo I can use to reproduce this problem?

**Comment by ttys3** [comment] 2022-01-28 13:38
@j-hui  OK, I'll upload a zip with demo project to re-produce this:

![image](https://user-images.githubusercontent.com/41882455/151556188-9641c524-39dc-454a-abfb-f9d3ba7eb42b.png)

[fidget-nvim-go-mod-demo.zip](https://github.com/j-hui/fidget.nvim/files/7959009/fidget-nvim-go-mod-demo.zip)

**Comment by j-hui** [comment] 2022-01-28 15:22
thanks @ttys3 ! I was able to repro the issue.

Turns out `string.format` does not support any format specifier with n > 99. Can you try again with the latest commit I pushed to that branch?

**Comment by ssoriche** [comment] 2022-01-28 15:31
I have not tried the branch (yet), but during my own experimentation with passing `%99s` to `string.format()` I noticed the same thing, `gopls` task never completed, and the spinner used considerable CPU.

**Comment by j-hui** [comment] 2022-01-28 15:39
@ttys3 may I create an issue on gopls with the test repo you sent me?

**Comment by ssoriche** [comment] 2022-01-28 15:41
Using the `truncate-messages` branch, I was able to successfully start neovim with fidget displaying progress, and the task did stop.

I'll continue to use this branch throughout the day and if I see any different behaviour report it here.

**Comment by ttys3** [comment] 2022-01-28 15:49
> @ttys3 may I create an issue on gopls with the test repo you sent me?

Of course, it is just a demo and does not involve any private information

**Comment by ssoriche** [comment] 2022-01-28 18:27
I am getting the constant running `gopls` again, but this time I can see the message because it is truncated:

```
err: exit status 2: stderr: warning: ignoring symlink
```

This leaves the fidget status in the corner, with the spinner continuing.

**Comment by j-hui** [comment] 2022-01-29 19:01
I landed #20 onto main, so this plugin should no longer spew errors when encountering extremely long messages.

The remaining issue with gopls spewing an extremely verbose diagnostic error and refusing to complete is tracked by golang/go#50885. If it turns out that the correct thing to do is to indeed timeout, I'll create another issue for that.

**Closed** 2022-01-29 19:02 UTC
Labels: bug

**Comment by ssoriche** [comment] 2022-01-31 20:46
Just wanted to add on to this with some information. I just had to force quit out of my terminal program with Activity Monitor telling me that neovim was using 100GB+ of memory. Fidget was running waiting for an update from gopls while I was involved in a meeting.

**Comment by j-hui** [comment] 2022-01-31 22:39
@ssoriche I'm very sorry to hear that. There's obviously no reason Fidget should need to allocate that much memory; I'll have to investigate where the leak is coming from.

**Comment by ssoriche** [comment] 2022-02-01 00:43
Thank you @j-hui, I just wanted to document that `gopls` decision on how to handle errors is impacting.
