### ISSUE TITLE
Rust proc macro finish not detected 

### ISSUE THREAD

**Issue by Amleto** [j-hui/fidget.nvim#201] opened 2024-01-15 15:16 UTC
When attaching in a rust project with many dependencies, fidget doesn't seem to detect rust analyzer finishing.

Normally the last proc macro build notification remains, along with the rotating dots.

I haven't managed to find a small repro yet. I've turned the logs on and don't really know what to look for.

When I open the repo with vscode it shows that rust analyzer finished loading/attaching ok

**Comment by j-hui** [comment] 2024-01-18 00:49
Thanks for filing this issue. I use Fidget for small- to medium-size
projects and haven't encountered this issue before, so it might not be
reproducible with a small example. But would you be able to point me to a
bigger repo where this is an issue?

Also, when it gets stuck, what does it show? Can you capture some logs of
this happening, to see if there's any hints there on what kind of
notifications lead to this issue?

A workaround might be to set the lsp.display.progress_ttl to a large
number, say, 300. Then if your proc macro hasn't completed in 5 min, the
notification should disappear on its own.

**Comment by Amleto** [comment] 2024-01-18 19:37
I will have to look around and try some open source repo to see if it's reproducible (I'm seeing the issue in my work repo)

If I disable proc macro builds with rust analyser then I've never seen the issue.

> Also, when it gets stuck, what does it show? 

> Normally the last proc macro build notification remains, along with the rotating dots.

I will gen some logs and paste a bit. Not sure what is of use from rust analyser, though, and they seem quite noisy

**Comment by Amleto** [comment] 2024-01-18 20:54
I see that the notification that "sticks" is the very last message that has `token = "rustAnaltzer/Building"`. But all of the proc macro builds seem to have the same one-off message.

The last proc macro progress message has
```
pending = {
["rustAnalyzer/Building"] = "Building"
}
```
But the next progress message has 
```
pending = {
["rustAnalyzer/Loading"] = "Loading",
["rustAnalyzer/Roots Scanned"] = "Roots Scanned"
}
```

And the final message has `pending` as empty

**Comment by Amleto** [comment] 2024-01-18 21:00
I checked out tokio repo and was able to reproduce straight away.

I will try the ttl setting

**Comment by j-hui** [comment] 2024-02-04 17:56
I see what's going on here. The progress buffer is getting overwhelmed with messages from Tokio---I say this because I can reproduce the issue on nvim 0.10 (which uses a ring buffer) but not on nvim 0.9 (which uses an unbounded queue). It's the same issue as #167.

Fidget is already responding to `LspUpdate` events [as soon as it can, by default](https://github.com/j-hui/fidget.nvim/blob/a3e1e79116ceb93d4c8c0ff432bf506b3213a24d/lua/fidget/progress.lua#L36), so I'm not sure there's much more that can be done here.

Can you see what happens if you set the `progress.lsp.progress_ringbuf_size` setting to something large, like 2048? That might fix it for you.

**Comment by CosmicSyntax** [comment] 2024-02-05 03:17
> Can you see what happens if you set the `progress.lsp.progress_ringbuf_size` setting to something large, like 2048? That might fix it for you.

@j-hui This worked for me. Thank you!

**Comment by Amleto** [comment] 2024-02-05 09:30
Yes, this looks to have done the job for me, too!

Thanks!

**Comment by j-hui** [comment] 2024-02-05 17:49
Oddly enough, I can no longer reproduce this issue at the moment, even without setting `progress.lsp.progress_ringbuf_size`... seems pretty finicky, but at least the workaround works.

In any case, I'm going close this issue.

**Closed by j-hui** 2024-02-05 17:49 UTC
Labels: bug, lsp
