### ISSUE TITLE
Fidget not starting with ClojureLSP

### ISSUE THREAD

**Issue by safv12** [j-hui/fidget.nvim#139] opened 2023-09-22 16:05 UTC
Based on the [ClojureLSP Capabilities site](https://clojure-lsp.io/capabilities/), the `$/progress` event is already implemented but when starting the LSP in Clojure files figet doesn't show.

**Nvim version**
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Lazy setup**

```
return {
  "j-hui/fidget.nvim",
  tag = "legacy",
  event = "LspAttach",
  config = function ()
    require("fidget").setup()
  end
}
```

**Comment by j-hui** [comment] 2023-11-11 01:47
@safv12 can you try with the updated implementation and let me know if this is still a problem?

If so, can you please set up test repo for me to reproduce the problem on my end (with setup instructions; I'm not familiar with Clojure development) so that I can debug it? Thanks!

**Comment by j-hui** [comment] 2023-11-11 03:16
Related: this Wiki page: https://github.com/j-hui/fidget.nvim/wiki/Known-compatible-LSP-servers

It's also worth checking if Fidget progress notifications are working with other language servers.

**Comment by Samy-33** [comment] 2023-11-17 02:47
As far as I understand, fidget progress only pops up when the LSP client attaches to the buffer

I have noticed clojure-lsp not attaching until all the preprocessing is done. That's why fidget progress doesn't show up.

Let me know if you find the same @safv12 .

When you open any clojure file, check the lsp client status using `:LspInfo`

**Comment by j-hui** [comment] 2023-11-21 18:49
Closing for now, since @Samy-33 's explanation makes sense to me. Feel free to re-open this issue if Fidget isn't showing progress even after clojure-lsp has attached.

**Closed by j-hui** 2023-11-21 18:49 UTC
Labels: bug, help wanted

**Comment by Samy-33** [comment] 2023-11-24 06:06
@j-hui, what's the behaviour when the client hasn't attached yet but the server still sends `$/progress` info?

It should work regardless of client being attached or not. Let me know what you think?

**Comment by j-hui** [comment] 2023-11-24 12:49
How would the server send `$/progress` messages if there's no attached client? (I don't actually know, I always assumed the messages could only be sent to attached clients).

In any case, it doesn't matter. Fidget doesn't assume the existence of any LSP client or server; it just uses an event handler for LspProgress and funnels messages to the notifications subsystem.

**Comment by Samy-33** [comment] 2023-11-25 08:13
You can see here, that LSP client sends `initialize` message on line#3 and server starts sending `$/progress` before sending back `initialized` message. So, yes that is possible.

```
[START][2023-11-24 11:34:08] LSP logging initiated
[INFO][2023-11-24 11:34:08] .../vim/lsp/rpc.lua:662	"Starting RPC client"	{  args = {},  cmd = "/Users/saket/.local/share/nvim/mason/bin/clojure-lsp",  extra = {    cwd = "/Users/saket/Documents/oliv/autosched"  }}
[DEBUG][2023-11-24 11:34:08] .../vim/lsp/rpc.lua:284	"rpc.send"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      textDocument = {        callHierarchy = {          dynamicRegistration = false        },        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }            }          },          dataSupport = true,          dynamicRegistration = false,          isPreferredSupport = true,          resolveSupport = {            properties = { "edit" }          }        },        completion = {          completionItem = {            commitCharactersSupport = true,            deprecatedSupport = true,            documentationFormat = { "markdown", "plaintext" },            insertReplaceSupport = true,            insertTextModeSupport = {              valueSet = { 1, 2 }            },            labelDetailsSupport = true,            preselectSupport = true,            resolveSupport = {              properties = { "documentation", "detail", "additionalTextEdits", "sortText", "filterText", "insertText", "textEdit", "insertTextFormat", "insertTextMode" }            },            snippetSupport = true,            tagSupport = {              valueSet = { 1 }            }          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }          },          completionList = {            itemDefaults = { "commitCharacters", "editRange", "insertTextFormat", "insertTextMode", "data" }          },          contextSupport = true,          dynamicRegistration = false,          insertTextMode = 1        },        declaration = {          linkSupport = true        },        definition = {          linkSupport = true        },        documentHighlight = {          dynamicRegistration = false        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false        },        implementation = {          linkSupport = true        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 }          }        },        references = {          dynamicRegistration = false        },        rename = {          dynamicRegistration = false,          prepareSupport = true        },        semanticTokens = {          augmentsSyntaxTokens = true,          dynamicRegistration = false,          formats = { "relative" },          multilineTokenSupport = false,          overlappingTokenSupport = true,          requests = {            full = {              delta = true            },            range = false          },          serverCancelSupport = false,          tokenModifiers = { "declaration", "definition", "readonly", "static", "deprecated", "abstract", "async", "modification", "documentation", "defaultLibrary" },          tokenTypes = { "namespace", "type", "class", "enum", "interface", "struct", "typeParameter", "parameter", "variable", "property", "enumMember", "event", "function", "method", "macro", "keyword", "modifier", "comment", "string", "number", "regexp", "operator", "decorator" }        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            activeParameterSupport = true,            documentationFormat = { "markdown", "plaintext" },            parameterInformation = {              labelOffsetSupport = true            }          }        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = true,          willSaveWaitUntil = true        },        typeDefinition = {          linkSupport = true        }      },      window = {        showDocument = {          support = true        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false          }        },        workDoneProgress = true      },      workspace = {        applyEdit = true,        configuration = true,        didChangeWatchedFiles = {          dynamicRegistration = false,          relativePatternSupport = true        },        semanticTokens = {          refreshSupport = true        },        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" }        },        workspaceFolders = true      }    },    clientInfo = {      name = "Neovim",      version = "0.9.4"    },    initializationOptions = vim.empty_dict(),    processId = 66843,    rootPath = "/Users/saket/Documents/oliv/autosched",    rootUri = "file:///Users/saket/Documents/oliv/autosched",    trace = "off",    workDoneToken = "work-done-token",    workspaceFolders = { {        name = "/Users/saket/Documents/oliv/autosched",        uri = "file:///Users/saket/Documents/oliv/autosched"      } }  }}
[DEBUG][2023-11-24 11:34:08] .../vim/lsp/rpc.lua:387	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "work-done-token",    value = {      kind = "begin",      percentage = 0,      title = "clojure-lsp"    }  }}
[DEBUG][2023-11-24 11:34:08] .../vim/lsp/rpc.lua:387	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "work-done-token",    value = {      kind = "report",      message = "Finding kondo config",      percentage = 5    }  }}
```

According to the [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize)
> Until the server has responded to the initialize request with an [InitializeResult](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeResult), the client must not send any additional requests or notifications to the server. In addition the server is not allowed to send any requests or notifications to the client until it has responded with an [InitializeResult](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeResult), with the exception that during the initialize request the server is allowed to send the notifications window/showMessage, window/logMessage and [telemetry/event](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#telemetry_event) as well as the window/showMessageRequest request to the client. **_In case the client sets up a progress token in the initialize params (e.g. property workDoneToken) the server is also allowed to use that token (and only that token) using the [$/progress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressBegin) notification sent from the server to the client._**

But again, fidget is not showing up even when we receive the `$/progress` messages from the LSP server.

**Comment by j-hui** [comment] 2023-11-28 17:15
I don't have a Clojure dev environment set up, so I am unable to reproduce this, but I've been lookin at the code and I have some theories about what might be happening.

First, I'm going to assume that the progress message is successfully received by [Neovim's `$/progress` handler](https://github.com/neovim/neovim/blob/35cec0de4acd351119230330f54b0a45f9823695/runtime/lua/vim/lsp/handlers.lua#L23-L57), though it would be great if you could validate this; just override the progress handler with a little logging:

```lua
local logger = require("fidget.logger")
local og = vim.lsp.handlers["$/progress"]
local function wrapped(x, result, ctx)
  logger.debug("got message from", ctx.client_id, vim.inspect(result))
  local res = og(x, result, ctx)
  logger.debug("nvim handler returned", res)
end
vim.lsp.handlers["$/progress"] = wrapped
```

On Fidget side, the `LspProgress` handler should call my `poll_for_messages()` function, which iterates through [active LSP clients](https://github.com/j-hui/fidget.nvim/blob/e732e65d6784ec1c34bb269ee69d635daffc4868/lua/fidget/progress/lsp.lua#L55). I just added some extra logging in e732e65d6784ec1c34bb269ee69d635daffc4868; please update Fidget (and configure to `INFO` level logging) and let me know if it's finding those messages.

**Comment by Samy-33** [comment] 2023-11-28 18:26
Hey John, do `active clients` mean the attached clients?

If so, it won't return clojure LSP as it's not yet attached ( but still
sending `$/progress` messages, which is allowed by the spec).

I will try to get more logs following the instructions you mentioned
tomorrow.

**Comment by Samy-33** [comment] 2023-11-28 18:37
In the mean time, if you want to reproduce the issues:

1. Make sure you have java 8+ JDK installed
2. Install clojure: https://clojure.org/guides/install_clojure
3. Install leiningen: https://leiningen.org/#install
4. Create a project using lein template:
`lein new luminus my-app +http-kit +shadow-cljs +reagent`
5. Go inside the project and open a `.clj` file.

**Comment by Samy-33** [comment] 2023-11-29 06:50
@j-hui logs with above mentioned logging:

```
[INFO  Wed Nov 29 12:20:02 2023] /lua/fidget.lua:18: fidget.nvim setup() complete.
[DEBUG Wed Nov 29 12:20:02 2023] /Users/saket/.config/nvim/lua/user/config/lsp.lua:64: got message from  1 {
  token = "work-done-token",
  value = {
    kind = "begin",
    percentage = 0,
    title = "clojure-lsp"
  }
}
[DEBUG Wed Nov 29 12:20:02 2023] ...r/neovim/HEAD-8c6b0a5/share/nvim/runtime/lua/vim/lsp.lua:1152: nvim handler returns 
[INFO  Wed Nov 29 12:20:02 2023] /lua/fidget/poll.lua:113: Poller ( progress ) polling once at 0.263s
[INFO  Wed Nov 29 12:20:02 2023] /lua/fidget/progress.lua:173: No LSP messages (that can be displayed)
[DEBUG Wed Nov 29 12:20:02 2023] /Users/saket/.config/nvim/lua/user/config/lsp.lua:64: got message from  1 {
  token = "work-done-token",
  value = {
    kind = "report",
    message = "Finding kondo config",
    percentage = 5
  }
}
[DEBUG Wed Nov 29 12:20:02 2023] ...r/neovim/HEAD-8c6b0a5/share/nvim/runtime/lua/vim/lsp.lua:1152: nvim handler returns 
[INFO  Wed Nov 29 12:20:02 2023] /lua/fidget/poll.lua:113: Poller ( progress ) polling once at 0.264s
[INFO  Wed Nov 29 12:20:02 2023] /lua/fidget/progress.lua:173: No LSP messages (that can be displayed)
[DEBUG Wed Nov 29 12:20:02 2023] /Users/saket/.config/nvim/lua/user/config/lsp.lua:64: got message from  1 {
  token = "work-done-token",
  value = {
    kind = "report",
    message = "Finding cache",
    percentage = 10
  }
}
[DEBUG Wed Nov 29 12:20:02 2023] ...r/neovim/HEAD-8c6b0a5/share/nvim/runtime/lua/vim/lsp.lua:1152: nvim handler returns 
[INFO  Wed Nov 29 12:20:02 2023] /lua/fidget/poll.lua:113: Poller ( progress ) polling once at 0.264s
[INFO  Wed Nov 29 12:20:02 2023] /lua/fidget/progress.lua:173: No LSP messages (that can be displayed)
[DEBUG Wed Nov 29 12:20:04 2023] /Users/saket/.config/nvim/lua/user/config/lsp.lua:64: got message from  1 {
  token = "work-done-token",
  value = {
    kind = "report",
    message = "Copying kondo configs",
    percentage = 15
  }
}
[DEBUG Wed Nov 29 12:20:04 2023] ...r/neovim/HEAD-8c6b0a5/share/nvim/runtime/lua/vim/lsp.lua:1152: nvim handler returns 
[INFO  Wed Nov 29 12:20:04 2023] /lua/fidget/poll.lua:113: Poller ( progress ) polling once at 2.597s
[INFO  Wed Nov 29 12:20:04 2023] /lua/fidget/progress.lua:173: No LSP messages (that can be displayed)
```
