### ISSUE TITLE
E523 when using clever-f

### ISSUE THREAD

**Issue by rockyzhang24** [j-hui/fidget.nvim#68] opened 2022-04-11 16:08 UTC
Hello,
I am using [clever-f](https://github.com/rhysd/clever-f.vim) and I got this issue

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/11582667/162783127-01e80338-0b72-4e79-ae6b-f60cdf5ecd3f.png">

It happens during the initialization of LSP server and after the initialization, the issue is gone. To reproduce, open any `lua` file (using `lua` because `lua` server needs longer time to initialize, so it will be easier to reproduce), then before the finish of the LSP server initialization, press `f` plus some char, then this issue appears. 

Thank you very much.

**Comment by wookayin** [comment] 2022-04-11 16:36
@rockyzhang24 it looks like your figet.nvim is outdated, because L216 does not read like `vim.schedule`. Are you sure it is on the latest version?

**Comment by rockyzhang24** [comment] 2022-04-11 16:39
Thanks. 
No, it is the latest fidget. I update my plugins everyday. My neovim is the latest nightly (NVIM v0.7.0-dev+1439-gda31e953b)

**Comment by rockyzhang24** [comment] 2022-04-11 16:54
Btw, the issue info is not the same for different filetype. 

In a `go` file, I got
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/11582667/162791023-4d9c53d4-4016-4d8a-bff7-dd74928ec7b0.png">

**Comment by wookayin** [comment] 2022-04-11 16:54
Sorry, I misread the stacktrace. You are right -- I can also reproduce the bug.

Indeed `vim.schedule` is from L386 (the bottommost line) and L216 reads
```
api.nvim_win_set_option(self.winid, "winblend", options.window.blend)
```

The problem is that the "deferred" `fidget:fmt()` call can still be executed by the event loop during the execution of `getchar()` (see https://github.com/vim/vim/issues/2811). I am looking into why.

**Comment by rockyzhang24** [comment] 2022-04-11 16:56
Thank you so much. I am not sure whether this issue is caused by `clever-f`. I already opened an issue there (https://github.com/rhysd/clever-f.vim/issues/65). Also, I am not sure whether this issue is related to https://github.com/neovim/neovim/issues/16278, i.e., caused by `<expr>` and `getchar()`. I have no ideas.

**Comment by wookayin** [comment] 2022-04-11 16:59
Also worth checking out a comment by @kevinhwang91 (https://www.reddit.com/r/neovim/comments/tzz5v7/share_a_ff_highlight_plugin/i42cy0d/) -- I use a similar plugin that maps `f`, namely `quick-scope`. Or @kevinhwang91's `nvim-fFHighlight` might be another alternative. 

Clever-f is not actively maintained these days, so you might want to switch to another similar plugin as a workaround. It's a bug that clever-f needs to fix, or neovim might be responsible for scheduling as `vim.schedule` is supposed to defer the execution *when it is available*.

**Comment by rockyzhang24** [comment] 2022-04-11 17:02
Okay. Thank you for your suggestions. 
I know this new plugin `nvim-fFHighlight` but it not supports `tT` highlight. 
For `quick-scope`, I tried it shortly before and I am worried its performance because it analyze each word in a line, not just the char I want to jump to.

**Comment by rockyzhang24** [comment] 2022-04-12 06:27
@wookayin Thank you so much for your investigation. Both fidget and clever-f are my must-have. Hope this can be fixed soon. Thanks again.

**Comment by wookayin** [comment] 2022-04-12 06:55
@rockyzhang24 Try out PR #69.

**Comment by wookayin** [comment] 2022-04-12 07:19
Yes, it is perfectly fine. Because E523 errors happens due to a 'textlock' (see `:h textlock`) and it only pertains to drawing of the fidget windows. Any internal states and data will remain intact. As you could test out, the fidget windows will simply won't be updated nor be spinning while it is in the operator-pending mode.

**Comment by rockyzhang24** [comment] 2022-04-12 07:42
@wookayin Okay, thank you for explaining it in detail. I just tested it, and I found another glitch. 

To reproduce it:
1. Open a `lua` file (because `lua` LSP takes longer to initialize)
2. Press `d` followed by `f`, now we are entering `Operator Pending` mode
3. Wait here without giving a char to `f`. We can see that fidget progress update and spinning pause as expect. Keep waiting, and we can see fidget left some ghost chars even though it has finished in background.4. 

<img width="1721" alt="Screen Shot 2022-04-12 at 00 37 57" src="https://user-images.githubusercontent.com/11582667/162906712-9cb6ca00-eb3a-4064-97bb-9b5b8394089c.png">

4. Then if we press `<ESC>` immediately after the ghost chars appear. The ghost will still be there and won't be removed any more. However, if we press `<ESC>` after a while, the error shows again

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/11582667/162907389-20e79ac6-ef66-457d-b5d2-f949a8e6d929.png">

Thank you!

**Comment by wookayin** [comment] 2022-04-12 07:47
@rockyzhang24 Good catch. Can you try again in the updated PR?

**Comment by kevinhwang91** [comment] 2022-04-12 07:47
> I tried nvim_get_mode() but it gives c = False, mode = "n" (normal mode).

Because `nvim_get_mode` is only for RPC API, `blocking = true` is always for Lua.

I don't think it's appropriate for fidget to fix this bug. There're maybe a lot of other async functions to encounter this issue. From the upstream is too hard to fix. From the clever-f avoid using <expr> must be refactored the cost is too expensive.

**Comment by wookayin** [comment] 2022-04-18 05:22
Again, the problem is that a function deferred by `vim.schedule(..)` will still be executed while operator is pending. We could safely skipping rendering, but when it comes to kill or closing, this workaround doesn't seem to work because it will lead to resource leakage or weird race condition. Fidget cannot easily tell when it is really available, despite the use of `vim.schedule`.

I think this requires an upstream fix, so no good solution for now. For the time being, I think #69 can be still merged to avoid most of E523 errors, and we can later improve the remaining case when fidget is trying to close.

@j-hui Any thoughts?

**Comment by wookayin** [comment] 2022-04-18 06:11
@rockyzhang24 I rewrote the logic and we can ignore the error when fidgets would be closed as well. This will make the annoying error not happen any more. However it cannot 100% eliminate "ghost chars" as I explained earlier; but we have some workaround like `:FidgetClose` so this should be usable enough.

**Comment by rockyzhang24** [comment] 2022-04-18 06:26
@wookayin Thank you so much for digging deeper into this issue and trying to come up with solutions. It looks like we have to wait for the upstream fix to make this issue solved completely. Could you please open an issue upstream? If I do, I'm afraid I cannot describe it clearly.

**Closed** 2022-04-19 03:41 UTC
Labels: bug, help wanted
