### ISSUE TITLE
LSP progress does not appear

### ISSUE THREAD

**Issue by okonmarcin** [j-hui/fidget.nvim#200] opened 2024-01-07 11:05 UTC
settings this thing as follow:

```lua
use {
  'j-hui/fidget.nvim',
  config = function()
    require("fidget").setup({
      notification = {
        window = {
          winblend = 0,
          relative = "editor"
        }
      }
    })
  end
}
```

However, I don't see any text appearing in the window. LSP is in place and it's working:
![Screenshot 2024-01-07 at 3 24 57 PM](https://github.com/j-hui/fidget.nvim/assets/7871186/ea1c4b4c-c5bd-4920-bc7b-10295f51d47b)

**Comment by j-hui** [comment] 2024-01-08 18:47
@okonmarcin can you please provide instructions for a minimally-reproducible setup? In particular: a sample nvim config, a test repo, and some indication of what LSP servers you're using.

You should also double-check that Fidget can display notifications using something like `:lua require("fidget").notify("test notification")`.

Furthermore, you can enable `logger.level = vim.log.levels.DEBUG` in the options and see if the attached LSP client is sending in the notifications in the first place. If it isn't, there's nothing for Fidget to display.

**Comment by Feel-ix-343** [comment] 2024-01-13 17:42
I am also getting this and there are polling messages in the log

**Comment by Feel-ix-343** [comment] 2024-01-13 17:56
Actually I am getting many of these

```
10858   │ [INFO  Sat 13 Jan 2024 12:54:30 PM EST] /lua/fidget/progress/lsp.lua:62: Polling me
        │ ssages from 1 ( rust_analyzer )
10859   │ [INFO  Sat 13 Jan 2024 12:54:30 PM EST] /lua/fidget/progress.lua:210: No LSP messag
        │ es (that can be displayed)
```

**Comment by boydkelly** [comment] 2024-01-20 21:54
I don't get any progress or messages.  i have not set any options, just
```
return {
  "j-hui/fidget.nvim",
  config = function()
    require("fidget").setup()
  end,
}
```
I am running lspzero and its all working fine.   I also have noice and I set both messages and lsp.progress to false.   Now i just get the old school messages at the bottom.

**Comment by j-hui** [comment] 2024-02-04 17:52
> No I just need to figure out how to get the other notifications.

@boydkelly  you might be looking for https://github.com/j-hui/fidget.nvim/blob/a3e1e79116ceb93d4c8c0ff432bf506b3213a24d/doc/fidget-option.txt#L521

> I am also getting this and there are polling messages in the log

@Feel-ix-343 it doesn't look like there are any messages to poll. I've pushed some updates recently that should give more informative logging, but ultimately if there's nothing that the LSP is sending, then there's nothing for Fidget to display.

Since there are no updates from OP @okonmarcin , I'm going to close this issue. Please open more specific if things continue to not work.

**Closed by j-hui** 2024-02-04 17:52 UTC
Labels: question, lsp
